Add core-metadata test cases
edgexfoundry/edgex-taf pull request #192
Opened 2020-10-06 03:20 UTC by cherrycl

Contain the following test cases.
- Device
- Device Profile without POST Method.
- Device Service without POST Method.

POST method for Device Profile and Device Service is in #189.
Fix #106 
Signed-off-by: Cherry Wang <cherry@iotechsys.com>

2020-10-12 04:44 UTC, jinlinGuan requested changes

2020-10-12 04:44 UTC, jinlinGuan commented on TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/DELETE-Negative.robot
> +    Then Should Return Status Code "400"
Should this return `423`?

2020-10-12 04:44 UTC, jinlinGuan commented on TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/DELETE-Negative.robot
> +    Then Should Return Status Code "400"
Also `423`?

2020-10-12 04:44 UTC, jinlinGuan commented on TAF/testScenarios/functionalTest/V2-API/core-metadata/device/GET-Negative.robot
> +ErrDeviceGET004 - Query all devices with sempty device service name
```suggestion
ErrDeviceGET004 - Query all devices with empty device service name
```

2020-10-12 04:44 UTC, jinlinGuan commented on TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/PUT-Negative-UploadFile.robot
> +${SUITE}          Core Metadata Device Profile PUT Positive Test Cases
```suggestion
${SUITE}          Core Metadata Device Profile PUT Negative Test Cases
```
and need a testcase for `Update device profile by upload file with duplicate profile name`

2020-10-12 05:03 UTC, cherrycl commented on TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/GET-Negative.robot
> +
Query with a non-existent manufacturer or model that belongs to positive tests. Skip it because it always returns an empty array.

2020-10-19 06:55 UTC, jinlinGuan approved these changes
LGTM

2020-10-19 06:55 UTC, merged