Start all services before running test scripts
edgexfoundry/edgex-taf pull request #421
Opened 2021-05-17 07:30 UTC by cherrycl

1. Start all services before running test scripts.
2. Update run-tests-on-local.md

Fix #315 
Signed-off-by: Cherry Wang <cherry@iotechsys.com>

2021-05-17 10:27 UTC, jinlinGuan requested changes

2021-05-17 10:27 UTC, jinlinGuan commented on TAF/utils/scripts/docker/run-tests.sh
> +              --exclude Skipped -u functionalTest/device-service -p device-virtual
```suggestion
              --exclude Skipped -u functionalTest/device-service -p device-modbus
```

2021-05-18 00:48 UTC, cherrycl commented on TAF/utils/scripts/docker/run-tests.sh
> +              --exclude Skipped -u functionalTest/device-service -p device-virtual
Fixed.

2021-05-18 08:00 UTC, jinlinGuan approved these changes
LGTM

2021-05-19 02:45 UTC, cherrycl commented
Removed deploy service steps for integration-test and update configuration.toml for device-services.

2021-05-19 08:10 UTC, jinlinGuan approved these changes
LGTM

2021-05-19 08:10 UTC, merged