feat: Add store and forward capability test cases
edgexfoundry/edgex-taf pull request #496
Opened 2021-07-09 08:07 UTC by cherrycl

Based on #211, writing the related scenarios.

Signed-off-by: Cherry Wang <cherry@iotechsys.com>

2021-07-09 15:17 UTC, lenny-intel submitted a review, later dismissed
Nice Job!

2021-07-12 01:51 UTC, jinlinGuan requested changes

2021-07-12 01:51 UTC, jinlinGuan commented on TAF/testScenarios/integrationTest/UC_end_to_end/export_store_forward.robot
> +    Given Set StoreAndForward.Enable=true, RetryInterval = 1s, MaxRetryCount=3 For app-http-export On Consul
```suggestion
    Given Set StoreAndForward.Enable=false, RetryInterval = 1s, MaxRetryCount=3 For app-http-export On Consul
```

2021-07-12 02:35 UTC, cherrycl commented on TAF/testScenarios/integrationTest/UC_end_to_end/export_store_forward.robot
> +    Given Set StoreAndForward.Enable=true, RetryInterval = 1s, MaxRetryCount=3 For app-http-export On Consul
Updated.

2021-07-12 02:47 UTC, jinlinGuan approved these changes
LGTM

2021-07-12 02:51 UTC, merged