Add POST device resource tests
edgexfoundry/edgex-taf pull request #625
Opened 2022-04-19 06:17 UTC by jumpingliu

feat #619

2022-04-20 01:48 UTC, cherrycl reviewed
For negative tests, not only validate the empty field, but need to contain the invalid data.
For positive tests, add tests to add single resource and multiple resource on each request.

2022-04-20 01:48 UTC, cherrycl commented on TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/POST-Negative-Deviceresource.robot
> +    And Should Return Status Code "201"
We don't have to contain this check here.

2022-04-22 03:26 UTC, jinlinGuan requested changes

2022-04-22 03:26 UTC, jinlinGuan commented on TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/POST-Positive-Deviceresource.robot
> +    And Item Index All Should Contain Status Code "201" And id
The response doesn't return id.
And add a check to verify the new device resources are added.

2022-04-22 03:26 UTC, jinlinGuan commented on TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/POST-Positive-Deviceresource.robot
> +    Given Create A Device Profile Basicinfo Only
Create a profile that already contains device resources instead.

2022-04-22 03:26 UTC, jinlinGuan commented on TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/POST-Positive-Deviceresource.robot
> +    And Item Index All Should Contain Status Code "201" And id
The response doesn't return id. 
And add a check to verify the new device resource is added.

2022-04-22 03:26 UTC, jinlinGuan commented on TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/POST-Positive-Deviceresource.robot
> +    # one resource > multiple basicinfo profiles
we don't need this testcase.

2022-04-22 03:26 UTC, jinlinGuan commented on TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/POST-Positive-Deviceresource.robot
> +    And Item Index All Should Contain Status Code "201" And id
The response doesn't return id.
And add a check to verify the new device resources are added to the profiles correctly.

2022-04-22 03:26 UTC, jinlinGuan commented on TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/POST-Negative-Deviceresource.robot
> +*** Settings ***
Add Content-Type and response time checks to all testcases.

2022-04-22 03:26 UTC, jinlinGuan commented on TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/POST-Negative-Deviceresource.robot
> +    Then Should Return Status Code "404"
This case should return status code 207 and the response code inside is 404.

2022-04-22 03:26 UTC, jinlinGuan commented on TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/POST-Negative-Deviceresource.robot
> +    Then Should Return Status Code "400"
This case should return status code 207 and the response code inside is 400.

2022-04-22 08:31 UTC, jinlinGuan requested changes

2022-04-22 08:31 UTC, jinlinGuan commented on TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/POST-Negative-Deviceresource.robot
> +*** Settings ***
Add `[Teardown]` to delete device profile to the testcases containing `Create A Device Profile Sample`.

2022-04-22 08:31 UTC, jinlinGuan commented on TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/POST-Positive-Deviceresource.robot
> +*** Settings ***
Add `[Teardown]` to each testcases to delete device profiles.

2022-04-25 01:29 UTC, jinlinGuan requested changes

2022-04-26 01:50 UTC, jinlinGuan approved these changes
LGTM

2022-04-26 01:50 UTC, merged