feat: Add DELETE device resource test
edgexfoundry/edgex-taf pull request #629
Opened 2022-04-19 10:43 UTC by jumpingliu

feat #621

2022-04-22 07:14 UTC, jinlinGuan requested changes

2022-04-22 07:14 UTC, jinlinGuan commented on TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/DELETE-Negative-Deviceresource.robot
> +    When Delete deviceResource By Name
Should create a normal device profile and delete device resource by non-existent deviceResource name

2022-04-22 07:14 UTC, jinlinGuan commented on TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/DELETE-Negative-Deviceresource.robot
> +*** Settings ***
Should add [Teardown] to each testcase to remove device profile created

2022-04-22 07:14 UTC, jinlinGuan commented on TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/DELETE-Negative-Deviceresource.robot
> +    And Response Time Should Be Less Than "${default_response_time_threshold}"ms
Should delete device profile and the assicated device created in this testcase

2022-04-22 07:14 UTC, jinlinGuan commented on TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/DELETE-Positive-Deviceresource.robot
> +Force Tags      v2-api
Use `skipped` instead.

2022-04-22 07:14 UTC, jinlinGuan commented on TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/DELETE-Positive-Deviceresource.robot
> +ProfileResourceDELETE001 - Delete deviceResource on device profile basicinfo only
This scenario is same as the one above, so this testcase can be removed.

2022-04-22 09:08 UTC, jumpingliu commented
Drop the commit so reopen the PR.

2022-04-25 01:32 UTC, jinlinGuan approved these changes
LGTM

2022-04-25 01:32 UTC, merged