feat: Implement testcase for PATCH basic info
edgexfoundry/edgex-taf pull request #645
Opened 2022-04-27 01:36 UTC by jumpingliu

feat #644

Signed-off-by: melody <melody@iotechsys.com>

**If your build fails**  due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-go/blob/main/.github/Contributing.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [ ] I am not introducing a new dependency (add notes below if you are)
- [ ] I have added unit tests for the new feature or bug fix (if not, why?)
- [ ] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [ ] I have opened a PR for the related docs change (if not, why?)
  <link to docs PR>

## Testing Instructions

## New Dependency Instructions (If applicable)

2022-04-27 08:37 UTC, jinlinGuan requested changes

2022-04-28 23:47 UTC, jumpingliu commented
Since keyword` Generate basicinfo ` is used in the positive and negative cases, I put it in the coreMetadataAPI file.

2022-04-29 09:47 UTC, jinlinGuan requested changes

2022-04-29 09:47 UTC, jinlinGuan commented on TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/PATCH-Negative-Basicinfo.robot
> +    [Teardown]  Delete device profile by name  Test-Profile-1
You have set`Test-Profile-1` to `test_profile` test variable in the `Generate a basicinfo sample for updating`, so use `test_profile` here instead.
```suggestion
    [Teardown]  Delete device profile by name  ${test_profile}
```

2022-04-29 09:47 UTC, jinlinGuan commented on TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/PATCH-Negative-Basicinfo.robot
> +    [Teardown]  Delete device profile by name  Test-Profile-1
```suggestion
    [Teardown]  Delete device profile by name  ${test_profile}
```

2022-05-03 03:57 UTC, jinlinGuan approved these changes
LGTM

2022-05-03 03:57 UTC, merged