feat: Update ASC functional tests to use new aes256 Encrypt algorithm
edgexfoundry/edgex-taf pull request #697
Opened 2022-08-12 07:20 UTC by cherrycl

Fix #541 implement decrypt validation

Signed-off-by: Cherry Wang <cherry@iotechsys.com>

**If your build fails**  due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-go/blob/main/.github/Contributing.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [ ] I am not introducing a new dependency (add notes below if you are)
- [ ] I have added unit tests for the new feature or bug fix (if not, why?)
- [X] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [ ] I have opened a PR for the related docs change (if not, why?)
  <link to docs PR>

## Testing Instructions

## New Dependency Instructions (If applicable)

2022-08-16 05:41 UTC, cherrycl commented
Hash validation is added on this PR. Fix #696

2022-08-16 13:36 UTC, bnevis-i commented
In order to provide a good example to users, we need to do like is done in https://github.com/codahale/etm/blob/master/etm.go#L204

That is, don't separate verifying the MAC from decrypting the data.  Must verify the MAC, THEN decrypt.

By separating the two operations, someone reading the test might think that only decrypt is needed, which might allow an attacker to recover the key by playing phony ciphertexts at at potential decryptor.

2022-08-17 00:28 UTC, cloudxxx8 commented
@bnevis-i they will be implemented in the same test.  we just separated this task to two issues (phases), because we need more time to investigate how to test the hash.

2022-08-23 12:04 UTC, cloudxxx8 commented
@bnevis-i all the tests are implemented in this PR although there are two issues. could you please help review it?

2022-08-23 13:41 UTC, bnevis-i submitted a review, later dismissed
Approved with strong reservations about splitting hash verification and decryption into two separable operations.

2022-08-23 14:18 UTC, cloudxxx8 commented
@bnevis-i , ok , looks like I misunderstood your concern about separating the two operations. I got it now. I will ask @cherrycl to modify it.

2022-08-23 14:29 UTC, cloudxxx8 requested changes

2022-08-25 03:06 UTC, cherrycl commented on TAF/utils/src/setup/aes256-decrypt.py
> +    print(compare_result)
Updated.

2022-08-25 03:06 UTC, cherrycl commented on TAF/testScenarios/functionalTest/V2-API/app-service/trigger/POST-positive.robot
> +    And Extract HASH Matches Calculated HASH
Updated.

2022-08-25 03:07 UTC, cherrycl commented
@bnevis-i @cloudxxx8 PR is updated, please help to review again. Thank you.

2022-08-25 03:09 UTC, cloudxxx8 approved these changes
LGTM

2022-08-25 03:12 UTC, cherrycl commented
Rebased PR.

2022-08-25 14:12 UTC, bnevis-i approved these changes
LGTM

2022-08-25 14:21 UTC, cloudxxx8 approved these changes
LGTM

2022-08-25 14:21 UTC, merged